# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.name = "Debian PostGreSQL"
  end

  config.vm.box = "grahamcox/trusty-postgres-9.4"
  config.vm.box_version = "1.0.0"
  
  config.vm.network :forwarded_port, guest: 3306, host: 3306
  config.vm.synced_folder ".", "/vagrant", :mount_options => ["dmode=777", "fmode=666"]
  config.vm.network "private_network", ip: "10.0.2.15"
end
