# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "debian/stretch64"

  config.vm.hostname = "node-mongo"
  config.vm.network "private_network",  ip: "10.0.2.15"
  config.vm.synced_folder ".", "/vagrant", :mount_options => ["dmode=777", "fmode=666"]
  config.vm.network :forwarded_port, guest: 27017, host: 27017


  config.vm.provider "virtualbox" do |v|
    v.name = "Debian MongoDB"
  end
  

  config.vm.provision :shell, path: "install.sh"

end